title: Hello, world! I'm Fabricio Rocha
description: > # this means to ignore newlines until "baseurl:"
  Blog de tecnologia
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.fabricior.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Fabricio Rocha # add your name
author-img: fabricio-rocha.jpg # add your photo
about-author: Desenvolvedor Backend | Java | Spring Boot | Kafka | Microserviço # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: rocha-fabricio # add your Github handle
social-linkedin: frabs # add your Linkedin handle
social-email: contato@fabricior.com.br # add your Email address

# Disqus
discus-identifier: fabricio # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
